### ISSUE TITLE
Jettons created based on this standard cannot be transfer

### ISSUE THREAD

**Issue by mikuh** [Ton-Dynasty/tondynasty-contracts#9]
![image](https://github.com/Ton-Dynasty/tondynasty-contracts/assets/16199680/7cddd685-191c-4608-ab4f-deddf211c9f3)

**Comment by alan890104** [comment]
Could you share your transaction hash for the testnet with us? We'll look into the issue right away—it might be related to the manually set storage and gas fees. Also, as a possible solution, would you mind trying to add a bit more TON coins, like 0.5, when you start the jetton transfer? This approach should help, especially since error code 37185 usually means there aren't enough funds for the transfer.

**Comment by alan890104** [comment]
@ipromise2324 I believe we should reduce gas consumption in light of the fee adjustments made in April. What's your opinion?

https://github.com/Ton-Dynasty/tondynasty-contracts/blob/45757ace724a6c72468a155a67959c929d129c30/contracts/packages/token/jetton/JettonWallet.tact#L66-L67

https://github.com/Ton-Dynasty/tondynasty-contracts/blob/45757ace724a6c72468a155a67959c929d129c30/contracts/packages/token/jetton/JettonWallet.tact#L209

**Comment by alan890104** [comment]
#10

**Comment by alan890104** [comment]
@mikuh May you pull the latest main branch and try it again, we have decrease the storage fee and gas fee preservation, i think it will work as expected.

**Comment by mikuh** [comment]
virtual const gasConsumption: Int = ton("0.05"); 
 virtual const minTonsForStorage: Int = ton("0.05"); 
After setting it to 0.01, it returned to normal.
